**Import the scipy.special module to gain access to the `factorial` function**

In [29]:
# Cell 1
import numpy as np
import scipy.special

**Create an integer array where $0\le x\le 20$**

In [30]:
# Cell 2
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**Set $z=0+\pi i$**

In [31]:
# Cell 3
z = complex(0, np.pi)
z

3.141592653589793j

**Create array $n=z^x$**

In [32]:
# Cell 4
n = np.power(z, x)
n

array([ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+3.14159265e+00j,
       -9.86960440e+00+0.00000000e+00j, -0.00000000e+00-3.10062767e+01j,
        9.74090910e+01+0.00000000e+00j,  0.00000000e+00+3.06019685e+02j,
       -9.61389194e+02+0.00000000e+00j, -0.00000000e+00-3.02029323e+03j,
        9.48853102e+03+0.00000000e+00j,  0.00000000e+00+2.98090993e+04j,
       -9.36480475e+04+0.00000000e+00j, -0.00000000e+00-2.94204018e+05j,
        9.24269182e+05+0.00000000e+00j,  0.00000000e+00+2.90367727e+06j,
       -9.12217118e+06+0.00000000e+00j, -0.00000000e+00-2.86581460e+07j,
        9.00322208e+07+0.00000000e+00j,  0.00000000e+00+2.82844564e+08j,
       -8.88582403e+08+0.00000000e+00j, -0.00000000e+00-2.79156395e+09j])

**Create array $d=x!$**

In [33]:
# Cell 5
d = scipy.special.factorial(x)
d

array([1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 6.00000000e+00,
       2.40000000e+01, 1.20000000e+02, 7.20000000e+02, 5.04000000e+03,
       4.03200000e+04, 3.62880000e+05, 3.62880000e+06, 3.99168000e+07,
       4.79001600e+08, 6.22702080e+09, 8.71782912e+10, 1.30767437e+12,
       2.09227899e+13, 3.55687428e+14, 6.40237371e+15, 1.21645100e+17])

**Divide every term in array $n$ by the corresponding term in array $d$**

In [34]:
# Cell 6
n / d

array([ 1.00000000e+00+0.00000000e+00j,  0.00000000e+00+3.14159265e+00j,
       -4.93480220e+00+0.00000000e+00j, -0.00000000e+00-5.16771278e+00j,
        4.05871213e+00+0.00000000e+00j,  0.00000000e+00+2.55016404e+00j,
       -1.33526277e+00+0.00000000e+00j, -0.00000000e+00-5.99264529e-01j,
        2.35330630e-01+0.00000000e+00j,  0.00000000e+00+8.21458866e-02j,
       -2.58068914e-02+0.00000000e+00j, -0.00000000e+00-7.37043095e-03j,
        1.92957431e-03+0.00000000e+00j,  0.00000000e+00+4.66302806e-04j,
       -1.04638105e-04+0.00000000e+00j, -0.00000000e+00-2.19153534e-05j,
        4.30306959e-06+0.00000000e+00j,  0.00000000e+00+7.95205400e-07j,
       -1.38789525e-07+0.00000000e+00j, -0.00000000e+00-2.29484290e-08j])

**Calculate $e^z=\sum\limits_{x=0}^{\infty}\frac{z^x}{x!}$ where $z=\pi i$**

In [35]:
# Cell 7
ez = np.sum(n / d)
np.round(ez, 8)

(-1-0j)